feat: display firmware version
hellqvio86/home_assistant_casambi pull request #68
Opened 2022-11-25 11:56 UTC by CFenner

2022-11-25 16:24 UTC, CFenner commented
Implemented with https://github.com/hellqvio86/aiocasambi/commit/43b8cbf4b87caa9fcf4d25882e79a0cabc29e05e

2022-11-25 16:25 UTC, CFenner commented on custom_components/casambi/casambi/CasambiEntity.py
> +            #sw_version = self.unit.firmwareVersion,
```suggestion
            sw_version = self.unit.firmwareVersion,
```

2022-11-25 16:25 UTC, CFenner commented on custom_components/casambi/casambi/CasambiEntity.py
> +            # TODO requires https://github.com/hellqvio86/aiocasambi/pull/19
```suggestion
```

2022-11-25 16:26 UTC, CFenner commented
I did not test this yet.

2022-11-25 22:24 UTC, CFenner commented
Looks good!

2022-11-26 07:26 UTC, hellqvio86 requested changes

2022-11-26 07:26 UTC, hellqvio86 commented on custom_components/casambi/casambi/CasambiEntity.py
> +            sw_version = self.unit.firmwareVersion,
Shouldn't `sw_version = self.unit.firmwareVersion,` be `sw_version = self.unit.firmware_version`? Since the getter is:

```
    @property
    def firmware_version(self) -> str:
        """
        Getter for firmware_version
        """

        return self._firmware_version
```

2022-11-26 09:00 UTC, CFenner commented on custom_components/casambi/casambi/CasambiEntity.py
> +            sw_version = self.unit.firmwareVersion,
```suggestion
            sw_version = self.unit.firmware_version,
```

2022-11-26 09:33 UTC, hellqvio86 approved these changes

2022-11-26 09:33 UTC, merged